(function(){
  const fonts = [
    'Aladin',
    'Amatic SC',
    'Annie Use Your Telescope',
    'Architects Daughter',
    'Bad Script',
    'Berkshire Swash',
    'Butterfly Kids',
    'Caveat',
    'Charm',
    'Chilanka',
    'Coming Soon',
    'Condiment',
    'Crafty Girls',
    'Dekko',
    'Delius',
    'Delius Swash Caps',
    'Delius Unicase',
    'Eagle Lake',
    'Felipa',
    'Fondamento',
    'Gaegu',
    'Gamja Flower',
    'Give You Glory',
    'Gloria Hallelujah',
    'Gochi Hand',
    'Handlee',
    'Hi Melody',
    'Indie Flower',
    'Itim',
    'Kalam',
    'Kavivanar',
    'Lakki Reddy',
    'League Script',
    'Loved by the King',
    'Mali',
    'Mansalva',
    'Merienda',
    'Molle',
    'Neucha',
    'Pangolin',
    'Patrick Hand',
    'Patrick Hand SC',
    'Quintessential',
    'Schoolbell',
    'Sedgwick Ave',
    'Shadows Into Light',
    'Shadows Into Light Two',
    'Sue Ellen Francisco',
    'Sunshiney',
    'Swanky and Moo Moo',
    'The Girl Next Door',
    'Tillana',
    'Waiting for the Sunrise'
  ];

  const pickedFont = fonts[Math.floor(Math.random()*fonts.length)];
  console.log('picked font is', pickedFont);
  document.body.style.fontFamily = `'${pickedFont}', cursive`;
  document.getElementById('fontFamily').innerText = pickedFont;
}());
